/* generated file, do not edit directly */

export const paletteVars = {
  gamma: {
    '0': 'var(--awsm-color-gamma-0)',
    '50': 'var(--awsm-color-gamma-50)',
    '100': 'var(--awsm-color-gamma-100)',
    '200': 'var(--awsm-color-gamma-200)',
    '300': 'var(--awsm-color-gamma-300)',
    '400': 'var(--awsm-color-gamma-400)',
    '500': 'var(--awsm-color-gamma-500)',
    '600': 'var(--awsm-color-gamma-600)',
    '700': 'var(--awsm-color-gamma-700)',
    '800': 'var(--awsm-color-gamma-800)',
    '900': 'var(--awsm-color-gamma-900)',
    '950': 'var(--awsm-color-gamma-950)',
    '1000': 'var(--awsm-color-gamma-1000)',
  },
  primary: {
    main: 'var(--awsm-color-primary-main)',
    mainRgb: 'var(--awsm-color-primary-main-rgb)',
    tint: 'var(--awsm-color-primary-tint)',
    shade: 'var(--awsm-color-primary-shade)',
    tone: 'var(--awsm-color-primary-tone)',
    contrast: 'var(--awsm-color-primary-contrast)',
    gamma: {
      '50': 'var(--awsm-color-primary-gamma-50)',
      '100': 'var(--awsm-color-primary-gamma-100)',
      '200': 'var(--awsm-color-primary-gamma-200)',
      '300': 'var(--awsm-color-primary-gamma-300)',
      '400': 'var(--awsm-color-primary-gamma-400)',
      '500': 'var(--awsm-color-primary-gamma-500)',
      '600': 'var(--awsm-color-primary-gamma-600)',
      '700': 'var(--awsm-color-primary-gamma-700)',
      '800': 'var(--awsm-color-primary-gamma-800)',
      '900': 'var(--awsm-color-primary-gamma-900)',
      '950': 'var(--awsm-color-primary-gamma-950)',
    },
  },
  secondary: {
    main: 'var(--awsm-color-secondary-main)',
    mainRgb: 'var(--awsm-color-secondary-main-rgb)',
    tint: 'var(--awsm-color-secondary-tint)',
    shade: 'var(--awsm-color-secondary-shade)',
    tone: 'var(--awsm-color-secondary-tone)',
    contrast: 'var(--awsm-color-secondary-contrast)',
    gamma: {
      '50': 'var(--awsm-color-secondary-gamma-50)',
      '100': 'var(--awsm-color-secondary-gamma-100)',
      '200': 'var(--awsm-color-secondary-gamma-200)',
      '300': 'var(--awsm-color-secondary-gamma-300)',
      '400': 'var(--awsm-color-secondary-gamma-400)',
      '500': 'var(--awsm-color-secondary-gamma-500)',
      '600': 'var(--awsm-color-secondary-gamma-600)',
      '700': 'var(--awsm-color-secondary-gamma-700)',
      '800': 'var(--awsm-color-secondary-gamma-800)',
      '900': 'var(--awsm-color-secondary-gamma-900)',
      '950': 'var(--awsm-color-secondary-gamma-950)',
    },
  },
  safe: {
    main: 'var(--awsm-color-safe-main)',
    mainRgb: 'var(--awsm-color-safe-main-rgb)',
    tint: 'var(--awsm-color-safe-tint)',
    shade: 'var(--awsm-color-safe-shade)',
    tone: 'var(--awsm-color-safe-tone)',
    contrast: 'var(--awsm-color-safe-contrast)',
  },
  alert: {
    main: 'var(--awsm-color-alert-main)',
    mainRgb: 'var(--awsm-color-alert-main-rgb)',
    tint: 'var(--awsm-color-alert-tint)',
    shade: 'var(--awsm-color-alert-shade)',
    tone: 'var(--awsm-color-alert-tone)',
    contrast: 'var(--awsm-color-alert-contrast)',
  },
  info: {
    main: 'var(--awsm-color-info-main)',
    mainRgb: 'var(--awsm-color-info-main-rgb)',
    tint: 'var(--awsm-color-info-tint)',
    shade: 'var(--awsm-color-info-shade)',
    tone: 'var(--awsm-color-info-tone)',
    contrast: 'var(--awsm-color-info-contrast)',
  },
  warning: {
    main: 'var(--awsm-color-warning-main)',
    mainRgb: 'var(--awsm-color-warning-main-rgb)',
    tint: 'var(--awsm-color-warning-tint)',
    shade: 'var(--awsm-color-warning-shade)',
    tone: 'var(--awsm-color-warning-tone)',
    contrast: 'var(--awsm-color-warning-contrast)',
  },
  text: {
    strong: 'var(--awsm-color-text-strong)',
    regular: 'var(--awsm-color-text-regular)',
    subtle: 'var(--awsm-color-text-subtle)',
    muted: 'var(--awsm-color-text-muted)',
  },
  background: {
    regular: 'var(--awsm-color-background-regular)',
    subtle: 'var(--awsm-color-background-subtle)',
    muted: 'var(--awsm-color-background-muted)',
  },
  shadow: 'var(--awsm-color-shadow)',
  shadowRgb: 'var(--awsm-color-shadow-rgb)',
  focusRing: 'var(--awsm-color-focus-ring)',
};
